### ISSUE TITLE
Start and end value

### ISSUE THREAD

**Issue by jamespet77** [srinivasa-dev/wheel_slider#11]
Is it possible too specify a start and end value.  
Example 
Start value : 10
End value : 15
10, 11, 12,13, 14, 15 are the slider options?

**Comment by WaseemAlqahwaji** [comment]
same issue i can't find thing would help me with start value

**Comment by WaseemAlqahwaji** [comment]
> Is it possible too specify a start and end value. Example Start value : 10 End value : 15 10, 11, 12,13, 14, 15 are the slider options?

hey my friend, you can do it with .customWidget constructor 

WheelSlider.customWidget(
          perspective: 0.002,
          scrollPhysics: const BouncingScrollPhysics(),
          totalCount: 90,
          initValue: 6,
          verticalListWidth: double.infinity,
          customPointer: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              pointerContainer(),
              Gap(calculateSelectedTextHeight(context) + 10.h),
              pointerContainer(),
            ],
          ),
          horizontal: false,
          isInfinite: false,
          isVibrate: false,
          itemSize: calculateSelectedTextHeight(context),
          onValueChanged: (value) {
            setState(() {
              context.read<UserDetailsCubit>().currentAge = value;
            });
          },
          children: List.generate(65, (index) {
            return Align(
              alignment: Alignment.center,
              child: RichText(
                text: TextSpan(
                  style: context.read<UserDetailsCubit>().currentAge == index
                      ? selectedNumberStyle
                      : TextStyle(
                          color: Colors.grey.withOpacity(.7),
                          fontSize: 24.0.sp,
                          fontFamily: "Cairo",
                        ),
                  children: [
                    TextSpan(
                      text: (index + 18).toString(),
                    )
                  ],
                ),
              ),
            );
          }),
        ),

**Comment by sybrands-place** [comment]
You can solve this by

```dart
final min = 20;
final max = 200;

WheelSlider(
  horizontalListWidth: 360,
  totalCount: max - min,
  initValue: (max / 2) - min,
  isInfinite: false,
  onValueChanged: (val) {
    setState(() {
      _current = (val + min);
    });
  },
  isVibrate: false,
),

```
