### ISSUE TITLE
Wheel chooser breaking changes.

### ISSUE THREAD

**Issue by flutterWithChris** [srinivasa-dev/wheel_slider#3]
Here's the latest changelog for `wheel_chooser`. It includes new parameters that need to be initialized:

v1.1.0
- New 'choices' constructor.
- Added WheelChooser.number.
- Added physics property.

Link to changelog: https://pub.dev/packages/wheel_chooser/changelog

**Comment by srinivasa-dev** [comment]
I have updated to the latest version and added a few additional features.

Link to changelog: [[v1.1.0]](https://pub.dev/packages/wheel_slider/changelog)

**Comment by flutterWithChris** [comment]
Thank you!
