### ISSUE TITLE
how can i choose minute values ?

### ISSUE THREAD

**Issue by jesussmile** [srinivasa-dev/wheel_slider#6]
i want to choose values like 0.001, 0.002,0.003 till 1 ? how to add increment ?

**Comment by BijoSabuDev** [comment]
hey srinivasa, please modify the library to also accept double values.right now only integers are allowed.

**Comment by srinivasa-dev** [comment]
Hey Bijo,

As my library depends on another package and they don't support data type double I have requested the concerned developer to make this change. Only then I can accommodate the requested change.

In the mean time if needed you can round the double to int and use the package.

**Comment by BijoSabuDev** [comment]
Hey Srinivasa,

Thanks for the reply, I appreciate your gesture towards the concern I raised. I actually wanted to show decimal itself when showing the slider, in that case converting to int might not be feasible. I have used in the inbuilt list scroll for the time being. Thanks again!

Regards,
Bijo Sabu
________________________________

**Comment by srinivasa-dev** [comment]
Hey Bijo,

Got it, let me see if I can get that done in my library.
Assuming your need for this change at the earliest, will try to resolve this asap.

**Comment by BijoSabuDev** [comment]
Hi Srinivasa,

Thanks for the help!

Best Regards.

________________________________
